# Generated by Django 5.2.6 on 2025-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_document_document_alter_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
